# Generated by Django 4.2.5 on 2024-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('DockerName', models.CharField(max_length=255)),
                ('DockerPort', models.CharField(max_length=255)),
                ('UrlPath', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Visable', models.BooleanField(default=False)),
            ],
        ),
    ]
