# Generated by Django 4.2.5 on 2024-06-10 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0003_topic_keyvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('Score_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserScore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
