# Generated by Django 4.2.3 on 2025-02-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='UrlPath',
        ),
    ]
