# Generated by Django 4.2.19 on 2025-02-20 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0005_delete_notice_remove_topic_urlpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDockerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxDockerNumber', models.IntegerField(default=1)),
                ('RunDockerNumber', models.IntegerField(default=0)),
                ('RunDockerId', models.CharField(max_length=255)),
                ('DockerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
