# Generated by Django 4.2.19 on 2025-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_userdockerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdockerdata',
            name='RunDockerTopicId',
            field=models.IntegerField(default=-1),
        ),
    ]
