# Generated by Django 4.2.19 on 2025-02-24 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0007_userdockerdata_rundockertopicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='SubmitTopics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSubmitTopic', to='topic.topic'),
        ),
        migrations.AlterField(
            model_name='score',
            name='Score_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
