# Generated by Django 4.2.19 on 2025-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_score_submittopics_alter_score_score_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='SubmitTopics',
        ),
        migrations.AddField(
            model_name='score',
            name='SubmitTopics',
            field=models.ManyToManyField(related_name='UserSubmitTopic', to='topic.topic'),
        ),
    ]
