# Generated by Django 4.2.5 on 2023-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('token', models.CharField(max_length=50)),
                ('attackscore', models.IntegerField(default=100)),
                ('checkscore', models.IntegerField(default=100)),
                ('initscore', models.IntegerField(default=1000)),
                ('starttime', models.DateTimeField()),
                ('rounttime', models.DurationField()),
                ('rountnumber', models.PositiveIntegerField(default=12)),
                ('currentrount', models.IntegerField(default=0)),
                ('flagformat', models.CharField(default='flag', max_length=10)),
                ('teams', models.ManyToManyField(related_name='competitions', to='Team.team')),
            ],
        ),
    ]
