# Generated by Django 4.2.5 on 2023-10-04 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 11, 16, 16, 749247, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flag',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 11, 16, 22, 686555, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
