# Generated by Django 4.2.5 on 2023-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_flag_endtime_flag_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='IsActivate',
            field=models.BooleanField(default=False),
        ),
    ]
