# Generated by Django 4.2.5 on 2023-10-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_information'),
        ('competition', '0004_competition_isactivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='attackscore',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='checkscore',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='initscore',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackscore', models.IntegerField(default=100)),
                ('checkscore', models.IntegerField(default=100)),
                ('initscore', models.IntegerField(default=1000)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('imagename', models.CharField(max_length=255, unique=True)),
                ('shellcmd', models.CharField(max_length=255)),
                ('external', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='competition.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Team.team')),
            ],
        ),
    ]
