# Generated by Django 4.2.5 on 2023-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_remove_competition_attackscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sshname',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='sshpassword',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
