# Generated by Django 4.2.5 on 2023-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_topic_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='interior',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='interiorpath',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='external',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sshname',
            field=models.CharField(max_length=30),
        ),
    ]
