# Generated by Django 4.2.5 on 2023-10-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_information'),
        ('competition', '0009_topic_flagpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='shellcmd',
        ),
        migrations.AlterField(
            model_name='topic',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='competition.competition'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Team.team'),
        ),
    ]
