# Generated by Django 4.2.5 on 2023-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_remove_topic_shellcmd_alter_topic_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='external',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='interior',
            field=models.CharField(max_length=255),
        ),
    ]
